#!/bin/bash

echo
echo -e "\033[1mThis might time a little while . . . go grab a beer.\033[0m"
echo
sleep 3
tput sgr0

cd components/elasticsearch
docker build -t schvin/elasticsearch .

cd ../../components/carbon
docker build -t schvin/carbon .

cd ../../components/graphite
docker build -t schvin/graphite .

cd ../../components/grafana
docker build -t schvin/grafana .

cd ../../components/nginx
docker build -t schvin/nginx .

cd ../../components/statsd
docker build -t schvin/statsd .

cd ../../
docker build -t schvin/dockerana .

echo; echo
echo -e "\033[1mOk! You're ready to start dockerana.\033[0m"
