#!/bin/bash

echo
echo -e "\033[1mThis might take a little while . . . go grab a beer.\033[0m"
echo
sleep 3
tput sgr0

cd components/elasticsearch
docker build -t dockerana/elasticsearch .

cd ../../components/carbon
docker build -t dockerana/carbon .

cd ../../components/graphite
docker build -t dockerana/graphite .

cd ../../components/grafana
docker build -t dockerana/grafana .

cd ../../components/nginx
docker build -t dockerana/nginx .

cd ../../components/statsd
docker build -t dockerana/statsd .

cd ../../
docker build -t dockerana/dockerana .

echo; echo
echo -e "\033[1mOk! You're ready to start dockerana.\033[0m"
