#!/bin/bash

echo "starting elasticsearch . . ."
docker kill dockerana-elasticsearch >/dev/null 2>&1
docker rm dockerana-elasticsearch >/dev/null 2>&1
docker run -d \
           -p 9200:9200 \
           --name dockerana-elasticsearch schvin/elasticsearch

echo "starting graphite . . ."
docker kill dockerana-graphite >/dev/null 2>&1
docker rm dockerana-graphite >/dev/null 2>&1
docker run -d \
           -p 8080:80 \
           -p 2003:2003 \
           -p 2004:2004 \
           -p 7002:7002 \
           -p 8125:8125/udp \
           --name dockerana-graphite schvin/graphite

echo "starting grafana . . ."
docker kill dockerana-grafana >/dev/null 2>&1
docker rm dockerana-grafana >/dev/null 2>&1
docker run -d -P --name dockerana-grafana schvin/grafana

echo "starting docker host syslog ingest . . ."
docker run -d -v /var/log:/tmp/log:ro --link graphite:graphite schvin/dockerana

PORT=`docker ps | grep dockerana-grafana | sed -e 's/.*://' | sed -e 's/\-.*//'`
HOST=`/usr/bin/env | grep DOCKER_HOST | perl -pe 's/.*\/([0-9\.]+):.*/$1/'`
echo "Everything is running, go check out http://$HOST:$PORT"
