#!/bin/bash

echo "starting elasticsearch . . ."
docker kill dockerana-elasticsearch >/dev/null 2>&1
docker rm dockerana-elasticsearch >/dev/null 2>&1
docker run -d \
           -p 9200:9200 \
           --name dockerana-elasticsearch schvin/elasticsearch

echo "starting carbon . . ."
docker kill dockerana-carbon >/dev/null 2>&1
docker rm dockerana-carbon >/dev/null 2>&1
docker run -d \
           -p 2004:2004 \
           -p 7002:7002 \
           -v /opt/graphite \
           --name dockerana-carbon schvin/carbon

echo "starting graphite . . ."
docker kill dockerana-graphite >/dev/null 2>&1
docker rm dockerana-graphite >/dev/null 2>&1
docker run -d \
           --volumes-from dockerana-carbon
           --name dockerana-graphite schvin/graphite

echo "starting nginx . . ."
docker kill dockerana-nginx >/dev/null 2>&1
docker rm dockerana-nginx >/dev/null 2>&1
docker run -d -p 8080:80 --name dockerana-nginx --link dockerana-graphite:dockerana-graphite-link schvin/nginx

echo "starting statsd . . ."
docker kill dockerana-statsd >/dev/null 2>&1
docker rm dockerana-statsd >/dev/null 2>&1
docker run -d \
           -p 8126:8126 \
           -p 8125:8125/udp \
           --name dockerana-statsd --link dockerana-carbon:dockerana-carbon-link schvin/statsd

echo "starting grafana . . ."
docker kill dockerana-grafana >/dev/null 2>&1
docker rm dockerana-grafana >/dev/null 2>&1
docker run -d -P --name dockerana-grafana schvin/grafana

echo "starting docker host syslog ingest . . ."
docker kill dockerana >/dev/null 2>&1
docker rm dockerana >/dev/null 2>&1
docker run -d -v /var/log:/tmp/log:ro --link dockerana-graphite:graphite --name dockerana schvin/dockerana

PORT=`docker ps | grep dockerana-grafana | sed -e 's/.*://' | sed -e 's/\-.*//'`
HOST=`/usr/bin/env | grep DOCKER_HOST | perl -pe 's/.*\/([0-9\.]+):.*/$1/'`
echo "Everything is running, go check out http://$HOST:$PORT"
