#!/bin/bash

echo "stopping elasticsearch . . ."
docker kill dockerana-elasticsearch >/dev/null 2>&1
docker rm dockerana-elasticsearch >/dev/null 2>&1

echo "stopping graphite . . ."
docker kill dockerana-graphite >/dev/null 2>&1
docker rm dockerana-graphite >/dev/null 2>&1

echo "stopping grafana . . ."
docker kill dockerana-grafana >/dev/null 2>&1
docker rm dockerana-grafana >/dev/null 2>&1

echo "stopping dockerana . . ."
docker kill dockerana >/dev/null 2>&1
docker rm dockerana >/dev/null 2>&1

echo "Everything is stopped."
